---

- name: copy template answers.yaml
  template:
    src: answers.yaml.j2
    dest: "{{st2_answers_file_path}}"
    owner: 'www-data'
    group: 'www-data'
    mode: 0770
  register: answers_yml

- name: run installer
  command: "bash {{st2_install_script_path}} -a {{st2_answers_file_path}}"
  when: answers_yml.changed

- name: create needed directories
  file: path="{{ item }}" mode=0755 state=directory
  with_items:
  - '/etc/st2'
  - '/etc/nginx/sites-available'
  - '/root/.st2'
  - '/opt/stackstorm/packs/st2'

# The puppet installer / install.sh overwrites st2.conf with other values.
- name: copy template st2.conf
  template:
    src: st2.conf.j2
    dest: /etc/st2/st2.conf
    owner: 'root'
    group: 'root'
    mode: 0644
  notify:
   - restart st2

# The installer/install.sh overwrites the nginx configuration
- name: copy nginx templates
  template:
    src: "{{item}}.j2"
    dest: "/etc/nginx/sites-available/{{item}}"
    owner: 'root'
    group: 'root'
    mode: 0644
  with_items:
   - st2webui.conf
   - st2api.conf
   - st2auth.conf
  notify:
   - restart nginx

- name: copy hubot init script from template
  template:
    src: 'docker-hubot.init.j2'
    dest: '/etc/init.d/docker-hubot'
    owner: 'root'
    group: 'root'
    mode: 0755
  notify:
   - restart docker-hubot

- name: copy root user st2 cli config from template
  template:
    src: 'st2-dotfile-config.j2'
    dest: '/root/.st2/config'
    owner: 'root'
    group: 'root'
    mode: 0644

- name: copy /etc/profile.d/st2.sh config from template
  template:
    src: 'etc-profile.d-st2.sh.j2'
    dest: '/etc/profile.d/st2.sh'
    owner: 'root'
    group: 'root'
    mode: 0755

- name: create st2packs group
  group: name=st2packs state=present

- name: copy ...stackstorm/packs/st2/config.yaml
  template:
    src: 'packs-st2-config.yaml.j2'
    dest: '/opt/stackstorm/packs/st2/config.yaml'
    owner: 'root'
    group: 'st2packs'
    mode: 0775
  notify:
   - restart st2
