# Everything needed for deployment, in general. Stack specific needs go in deploy_$stack.yml

---

- name: add deploy group
  sudo: true
  group: name=deploy gid=2000
  tags:
    - deploy

- name: add deploy user
  sudo: true
  user: name=deploy uid=2000 group=2000
  tags:
    - deploy

- name: add deploy user ssh directory
  sudo: true
  file: state=directory path=/home/deploy/.ssh owner=deploy mode=700
  tags:
    - deploy

- name: stat path of /home/deploy/.ssh/id_rsa
  stat: path=/home/deploy/.ssh/id_rsa
  sudo: true
  register: id_rsa
  tags:
    - deploy

# - debug: msg="{{ id_rsa.stat.exists }} is id_rsa"
#   tags:
#     - ssh

# this shouldn't be necessary with profiles
- name: add deploy user ssh key (from s3)
  sudo: true
  s3: bucket="{{ administration_secrets_bucket }}" object="{{administration_deploy_key_path}}" dest=/home/deploy/.ssh/id_rsa mode=get
  # environment:
  #   AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
  #   AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
  when: id_rsa.stat.exists == False
  tags:
    - deploy

- name: ensure permissions on deploy user's ssh key
  sudo: true
  file: path=/home/deploy/.ssh/id_rsa owner=deploy group=deploy mode=600
  tags:
    - deploy

## ~/.aws/credentials
- name: add /home/deploy/.aws
  sudo: true
  file: state=directory path=/home/deploy/.aws owner=deploy mode=700
  tags:
    - aws_credentials

- name: stat path of /home/deploy/.aws/credentials
  stat: path=/home/deploy/.aws/credentials
  sudo: true
  register: aws_credentials
  tags:
    - aws_credentials

# - name: add /home/deploy/.aws/credentials (from s3)
#   sudo: true
#   s3: bucket={{ secrets_bucket }} object=/stacks/admin/admin/deploy_aws_credentials dest=/home/deploy/.aws/credentials mode=get
#   environment:
#     AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
#     AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
#   # For now, leaving it as always updating, otherwise updates are not pulled down. It's addressed here: https://github.com/ansible/ansible-modules-core/pull/1326
#   # when: aws_credentials.stat.exists == False
#   tags:
#     - aws_credentials

# - name: chown /home/deploy/.aws/credentials
#   sudo: true
#   file: state=file path=/home/deploy/.aws/credentials owner=deploy mode=400
#   tags:
#     - aws_credentials

# - name: Create infrastructure_repo_root
#   sudo: true
#   file: state=directory path={{infrastructure_repo_root}} owner=deploy recurse=true
#   tags:
#     - deploy
