---
# tasks file for stackstorm

- name: install packages
  become: true
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
   - build-essential
   - unzip
   - python-pip
   - python-dev
   - git
   - mysql-client
   - python-mysqldb
   - awscli
   - whois
  tags:
    - packages

- name: get install script
  get_url:
    url: "{{st2_aio_url}}"
    dest: "{{st2_install_script_path}}"

- include: configure.yml
- include: st2-users.yml
