---
# tasks file for admin

# Org wide vars
# - include_vars: ../../../vars.yml
#   tags:
#     - includes

- name: install packages
  sudo: true
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
   - build-essential
   - unzip
   - python-pip
   - python-dev
   - git
  tags:
    - packages

# This is erroring out with a hard-to-parse ssh error
# - name: Install pip packages
#   become: true
#   pip: name={{ item }} state=present
#   with_items:
#    - boto
#    - awscli
#   tags:
#     - packages

- name: download packer
  get_url: url=https://dl.bintray.com/mitchellh/packer/packer_0.8.6_linux_amd64.zip dest=/tmp/packer.zip

- name: unarchive packer
  sudo: true
  unarchive: src=/tmp/packer.zip dest=/usr/local/bin copy=no creates=/usr/local/bin/packer

- include: deployment.yml
