---

- name: encrypt root_cli password
  command: mkpasswd --method=SHA-512 "{{st2_root_cli_password}}"
  register: mkpasswd_root_cli_output
  changed_when: false

  # there doesn't seem to be an idempotent way via the user module to reliably set the password. 'always' will always update the password
  # 'on_create' will only do it on user creation. In this case, it is likely that the user already exists with a password set by the installer.
- name: set root_cli password
  user:
    name: root_cli
    password: "{{mkpasswd_root_cli_output.stdout}}"
    update_password: always
  changed_when: false


- name: encrypt chatops_bot password
  command: mkpasswd --method=SHA-512 "{{st2_chatops_bot_password}}"
  register: mkpasswd_chatops_bot_output
  changed_when: false

- name: set chatops_bot password
  user:
    name: chatops_bot
    password: "{{mkpasswd_chatops_bot_output.stdout}}"
    update_password: always
  changed_when: false
